<?php
namespace App\Repositories;

use App\Model\Post;
use App\Repositories\EloquentRepository;

class PostEloquentRepository extends EloquentRepository
{
    /**
     * Get model
     */
    public function getModel ()
    {
        return Post::class;
    }

    public function find($id)
    {
        return parent::find($id); // TODO: Change the autogenerated stub
    }

    public function create(array $attributes)
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }

    public function update($id, array $attributes)
    {
        return parent::update($id, $attributes); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }
}
